### ISSUE TITLE
Status on v2 parser

### ISSUE THREAD

**Issue by gshanemiller** [judofyr/glush#1]
I read with interest your post on Glush on hacknews. I wrote a grammer for BISON and can also attest to the frustration with shift/reduce errors. My side-project was to code a minimal language with if-then-else, functions, loops, strings, and operations on strings and intrinsic types like int with the goal of emitted LLVM code to be compiled into a binary. Fixing shift/reduce errors dragged on a lot longer than it should. So I'd definitely be interested in project status and ETA to alpha or beta level releases.

**Comment by judofyr** [comment]
Hi @rodgarrison and sorry for the delayed response.

Unfortunately I've recently been busy with other tasks recently and I haven't been able to give Glush the attention it deserves. Here the other week I was able to continue work on it again and now there's a PR where you can track the progress: https://github.com/judofyr/glush/pull/2.

I'm going to focus more on it in the following weeks/months, but I can't really give any concrete ETA at the moment.

**Comment by Zireael07** [comment]
It's been six years since the last update. Any news?
